###GET ALL incidentS
GET http://localhost:8000/api/incidents


###CREATE NEW incident
POST http://localhost:8000/api/incidents
Content-Type: application/json

{
    "line_id": "68c778a518b88688c1ccecf8",
    "vehicle_id": "68c8e14525100a0a2e993e57",
    "type":  "breakdown",
    "description": "description",
    "resolved_at": "2025-10-27T10:00:00Z"
}

###GET incident BY ID
GET http://localhost:8000/api/incidents/68ca305437dfbf8356201085

###UPDATE incident
PUT http://localhost:8000/api/incidents/68ca305437dfbf8356201085
Content-Type: application/json

{
    "description": "description updated"
}

###DELETE incident BY ID
DELETE  http://localhost:8000/api/incidents/68ca305437dfbf8356201085

### GET ALL INCIDENTS OF A LINE
GET http://localhost:8000/api/incidents?line_id=68c778a518b88688c1ccecf8&type=breakdown